// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0PzOAaiaOBa_WltEDT2itfUbkC3vNXM',
    appId: '1:366509567385:web:7189d927398099eb06f708',
    messagingSenderId: '366509567385',
    projectId: 'loginflutter-f0b84',
    authDomain: 'loginflutter-f0b84.firebaseapp.com',
    storageBucket: 'loginflutter-f0b84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbn64roIOnsdUQaN3AmL1CIihCZIwI9g',
    appId: '1:366509567385:android:3a0ca0d4db89bee406f708',
    messagingSenderId: '366509567385',
    projectId: 'loginflutter-f0b84',
    storageBucket: 'loginflutter-f0b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArbINdOY13wV7nqiQ2i_OMlRsKmHbySws',
    appId: '1:366509567385:ios:56f64fe1a03ad75d06f708',
    messagingSenderId: '366509567385',
    projectId: 'loginflutter-f0b84',
    storageBucket: 'loginflutter-f0b84.appspot.com',
    iosClientId:
        '366509567385-djjofc5lnevf782jus326tutj9b53hmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArbINdOY13wV7nqiQ2i_OMlRsKmHbySws',
    appId: '1:366509567385:ios:56f64fe1a03ad75d06f708',
    messagingSenderId: '366509567385',
    projectId: 'loginflutter-f0b84',
    storageBucket: 'loginflutter-f0b84.appspot.com',
    iosClientId:
        '366509567385-djjofc5lnevf782jus326tutj9b53hmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
